const catalogItems = [
  {
    id: 1,
    badge: 'Popular',
    name: 'Classic Mojito',
    category: 'cocktail',
    country: 'CU',
    detail: 'Glass',
    price: '$15',
    image: '/velvet-mist/src/assets/images/drink1.png',
    description:
      'Made with tequila, lime juice, and orange liqueur, the Margarita is easy to make and full of character. Add a salted rim for the perfect drink on summer nights.',
  },
  {
    id: 2,
    badge: 'Popular',
    name: 'Raspberry Mojito',
    category: 'cocktail',
    country: 'US',
    detail: 'Glass',
    price: '$17',
    image: '/velvet-mist/src/assets/images/drink2.png',
    description:
      "The Margarita is a classic that balances tangy lime, smooth tequila, and a touch of sweetness. Shaken, frozen, or on the rocks—it's always crisp & refreshing.",
  },
  {
    id: 3,
    name: 'Violet Breeze',
    category: 'cocktail',
    country: 'FR',
    detail: 'Chilled Glass',
    price: '$19',
    image: '/velvet-mist/src/assets/images/drink3.png',
    description:
      'Made with tequila, lime juice, and orange liqueur, the Margarita is easy to make and full of character. Add a salted rim for the perfect drink on summer nights.',
  },
  {
    id: 4,
    name: 'Curacao Mojito',
    category: 'cocktail',
    country: 'NL',
    detail: 'Glass',
    price: '$18',
    image: '/velvet-mist/src/assets/images/drink4.png',
    description:
      "Each cocktail is made with fresh ingredients and a passion for perfecting every pour, whether you're celebrating or simply relaxing.",
  },
  {
    id: 5,
    name: 'Tropical Bloom',
    category: 'mocktail',
    country: 'US',
    detail: 'Bottle',
    price: '$10',
    image: '/velvet-mist/src/assets/images/catalog/tropical-bloom.png',
    description:
      'A refreshing tropical blend with exotic fruits and floral notes.',
  },
  {
    id: 6,
    name: 'Passionfruit Mint',
    category: 'mocktail',
    country: 'US',
    detail: 'Bottle',
    price: '$12',
    image: '/velvet-mist/src/assets/images/catalog/passionfruit-mint.png',
    description:
      'Sweet passionfruit combined with fresh mint for a cooling experience.',
  },
  {
    id: 7,
    name: 'Citrus Glow',
    category: 'mocktail',
    country: 'CA',
    detail: '750 ml',
    price: '$20',
    image: '/velvet-mist/src/assets/images/catalog/citrus-glow.png',
    description: 'Zesty citrus blend that brightens your day with every sip.',
  },
  {
    id: 8,
    name: 'Lavender Fizz',
    category: 'mocktail',
    country: 'IE',
    detail: '600 ml',
    price: '$29',
    image: '/velvet-mist/src/assets/images/catalog/lavender-fizz.png',
    description:
      'Elegant lavender-infused sparkling drink with a delicate fizz.',
  },
  {
    id: 9,
    name: 'Midnight Manhattan',
    category: 'cocktail',
    country: 'US',
    detail: 'Glass',
    price: '$18',
    image: '/velvet-mist/src/assets/images/catalog/midnight-manhattan.png',
    description:
      'A sophisticated blend of whiskey and vermouth with a dark cherry finish.',
  },
  {
    id: 10,
    name: 'Santorini Sunset',
    category: 'cocktail',
    country: 'GR',
    detail: 'Bottle',
    price: '$32',
    image: '/velvet-mist/src/assets/images/catalog/santorini-sunset.png',
    description:
      'Inspired by Greek sunsets, this cocktail features ouzo and Mediterranean flavors.',
  },
  {
    id: 11,
    name: 'Tokyo Mule',
    category: 'cocktail',
    country: 'JP',
    detail: 'Copper Mug',
    price: '$22',
    image: '/velvet-mist/src/assets/images/catalog/tokyo-mule.png',
    description:
      'Japanese twist on the classic mule with sake and ginger beer.',
  },
  {
    id: 12,
    name: 'Havana Nights',
    category: 'cocktail',
    country: 'CU',
    detail: 'Glass',
    price: '$27',
    image: '/velvet-mist/src/assets/images/catalog/havana-nights.png',
    description:
      'Authentic Cuban rum cocktail with tropical fruit juices and mint.',
  },
  {
    id: 13,
    name: 'Berry Bliss',
    category: 'mocktail',
    country: 'US',
    detail: 'Bottle',
    price: '$15',
    image: '/velvet-mist/src/assets/images/catalog/berry-bliss.png',
    description: 'Mixed berry medley with a hint of vanilla for a sweet treat.',
  },
  {
    id: 14,
    name: 'Coconut Dream',
    category: 'mocktail',
    country: 'TH',
    detail: '500 ml',
    price: '$19',
    image: '/velvet-mist/src/assets/images/catalog/coconut-dream.png',
    description:
      'Creamy coconut blend with tropical fruits and a touch of lime.',
  },
  {
    id: 15,
    name: 'Mango Tango',
    category: 'mocktail',
    country: 'MX',
    detail: 'Glass',
    price: '$16',
    image: '/velvet-mist/src/assets/images/catalog/mango-tango.png',
    description:
      'Sweet mango puree with spicy chili and lime for a Mexican twist.',
  },
  {
    id: 16,
    name: 'Parisian Martini',
    category: 'cocktail',
    country: 'FR',
    detail: 'Chilled Glass',
    price: '$35',
    image: '/velvet-mist/src/assets/images/catalog/parisian-martini.png',
    description:
      'Elegant French martini with champagne and blackcurrant liqueur.',
  },
  {
    id: 17,
    name: 'London Fog',
    category: 'cocktail',
    country: 'UK',
    detail: 'Mug',
    price: '$24',
    image: '/velvet-mist/src/assets/images/catalog/london-fog.png',
    description: 'Gin-based cocktail with Earl Grey tea and lavender syrup.',
  },
  {
    id: 18,
    name: 'Rio Refresher',
    category: 'mocktail',
    country: 'BR',
    detail: '500 ml',
    price: '$17',
    image: '/velvet-mist/src/assets/images/catalog/rio-refresher.png',
    description:
      'Brazilian-inspired blend with açai, guarana, and citrus fruits.',
  },
  {
    id: 19,
    name: 'Sydney Sling',
    category: 'cocktail',
    country: 'AU',
    detail: 'Tall Glass',
    price: '$28',
    image: '/velvet-mist/src/assets/images/catalog/sydney-sling.png',
    description:
      'Australian version of Singapore sling with native botanicals.',
  },
  {
    id: 20,
    name: 'Moscow Mule',
    category: 'cocktail',
    country: 'RU',
    detail: 'Copper Mug',
    price: '$23',
    image: '/velvet-mist/src/assets/images/catalog/moscow-mule.png',
    description:
      'Classic vodka, ginger beer, and lime combination served ice cold.',
  },
  {
    id: 21,
    name: 'Vanilla Sky',
    category: 'mocktail',
    country: 'US',
    detail: 'Glass',
    price: '$14',
    image: '/velvet-mist/src/assets/images/catalog/vanilla-sky.png',
    description: 'Creamy vanilla and cloud-like foam with caramel drizzle.',
  },
  {
    id: 22,
    name: 'Ginger Spark',
    category: 'mocktail',
    country: 'CA',
    detail: 'Bottle',
    price: '$18',
    image: '/velvet-mist/src/assets/images/catalog/ginger-spark.png',
    description:
      'Spicy ginger ale with lemon and honey for a refreshing spark.',
  },
  {
    id: 23,
    name: 'Barcelona Breeze',
    category: 'cocktail',
    country: 'ES',
    detail: 'Glass',
    price: '$26',
    image: '/velvet-mist/src/assets/images/catalog/barcelona-breeze.png',
    description: 'Spanish cocktail with cava, citrus, and Mediterranean herbs.',
  },
  {
    id: 24,
    name: 'Kiwi Cooler',
    category: 'mocktail',
    country: 'NZ',
    detail: '500 ml',
    price: '$21',
    image: '/velvet-mist/src/assets/images/catalog/kiwi-cooler.png',
    description:
      'Fresh kiwi and mint infused sparkling water from New Zealand.',
  },
  {
    id: 25,
    name: 'Amsterdam Affair',
    category: 'cocktail',
    country: 'NL',
    detail: 'Tulip Glass',
    price: '$31',
    image: '/velvet-mist/src/assets/images/catalog/amsterdam-affair.png',
    description: 'Dutch genever cocktail with orange liqueur and bitters.',
  },
  {
    id: 26,
    name: 'Pineapple Paradise',
    category: 'mocktail',
    country: 'PH',
    detail: 'Glass',
    price: '$16',
    image: '/velvet-mist/src/assets/images/catalog/pineapple-paradise.png',
    description:
      'Sweet Philippine pineapple with coconut water and pandan leaves.',
  },
  {
    id: 27,
    name: 'Roman Holiday',
    category: 'cocktail',
    country: 'IT',
    detail: 'Wine Glass',
    price: '$33',
    image: '/velvet-mist/src/assets/images/catalog/roman-holiday.png',
    description: 'Italian aperitivo with prosecco, Aperol, and blood orange.',
  },
  {
    id: 28,
    name: 'Honey Lemon Twist',
    category: 'mocktail',
    country: 'US',
    detail: 'Bottle',
    price: '$13',
    image: '/velvet-mist/src/assets/images/catalog/honey-lemon-twist.png',
    description: 'Natural honey and fresh lemon with a twist of thyme.',
  },
  {
    id: 29,
    name: 'Dubai Gold',
    category: 'cocktail',
    country: 'AE',
    detail: 'Gold Rim Glass',
    price: '$45',
    image: '/velvet-mist/src/assets/images/catalog/dubai-gold.png',
    description:
      'Luxurious cocktail with gold leaf, saffron, and premium spirits.',
  },
  {
    id: 30,
    name: 'Watermelon Wave',
    category: 'mocktail',
    country: 'US',
    detail: 'Pitcher',
    price: '$25',
    image: '/velvet-mist/src/assets/images/catalog/watermelon-wave.png',
    description:
      'Fresh watermelon juice with basil and lime, perfect for sharing.',
  },
];

export { catalogItems };
